version: '3'
services:
  presentation:
    restart: always
    image: nginx:alpine
    container_name: presentation-nginx
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - "80:80"
  teamcity:
    container_name: "teamcity"
    image: "jetbrains/teamcity-server"
    ports:
    - "8080:8111"