version: '3'

services:

  presentation:
    image: nginx:alpine
    container_name: presentation-nginx
    volumes:
      - ./presentation:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always

  staging:
    container_name: staging
    build: ./docker/nginx-ssh-dotnet
    volumes:
      - ~/Library/Servers/staging/html:/usr/share/nginx/html
      - ~/Library/Servers/staging/octopus:/home/octopus
    ports:
      - "81:80"
      - "2222:22"
    restart: always

  production:
    container_name: production
    build: ./docker/nginx-ssh-dotnet
    volumes:
      - ~/Library/Servers/production/html:/usr/share/nginx/html
      - ~/Library/Servers/production/octopus:/home/octopus
    ports:
      - "82:80"
      - "2223:22"
    restart: always

  teamcity-server:
    container_name: "teamcity-server"
    image: "jetbrains/teamcity-server"
    volumes:
      - ~/Library/TeamCity/Data:/data/teamcity_server/datadir
      - ~/Library/TeamCity/Logs:/opt/teamcity/logs
      - ~/demo:/usr/demo
    ports:
    - "8111:8111"
    restart: always

  teamcity-agent:
    container_name: "teamcity-agent"
    build: ./docker/teamcity-agent-mono
    environment:
      - SERVER_URL=teamcity-server:8111
    volumes:
      - ~/Library/TeamCity/Agent:/data/teamcity_agent/conf
      - ~/demo:/usr/demo
    restart: always
